import test from 'node:test';
import assert from 'node:assert/strict';
import { resolveTargetContract, validateTargetPrerequisites, validateObservation, validateExpectationShape, validateStepExpectation, validateFlowSteps, captureRejectionReason, isVerifiedDecryptedAppFlow, isPngScreenshot, matchesUiNode, normalizeActivity } from '../../server/src/services/mobile/mobile-target-contract.ts';
import { normalizeRawFlow, parseFlowText } from '../../server/src/services/mobile/burp-capture-service.ts';
import { prepareMobileLab } from '../../server/src/services/mobile/mobile-lab-service.ts';
import { upsertMobileProfile } from '../../server/src/services/mobile/mobile-profile-service.ts';
import { discoveryCaptureRejection } from '../../server/src/services/mobile/discovery-capture-policy.ts';
import { database, profile, session, observation, flow, pkg, PNG } from './fixtures.mjs';
const required = ['require_apk_install','require_explicit_app_identity','require_explicit_tls_evidence','require_capture_app_identity','require_flow_steps','require_flow_assertions','require_apk_attestation','require_proxy_certificate'];
for (const flag of required) test(`strict contract cannot opt out of ${flag}`, () => { const p=profile();p.config_json[flag]=false; assert.equal(resolveTargetContract(p)[flag],true); });
for (const value of [NaN,Infinity,-1,0,'bad']) test(`invalid minimum ${String(value)} falls back to finite positive`,()=>{const p=profile();p.config_json.minimum_decrypted_flows=value;assert.equal(resolveTargetContract(p).minimum_decrypted_flows,1);});
test('offline mode is explicitly non-real',()=>{const p=profile();p.config_json.offline_simulator=true;assert.equal(resolveTargetContract(p).strict_real_e2e,false);});
test('legacy use_simulator cannot silently change strict runtime',()=>{const p=profile();p.config_json.use_simulator=true;assert.equal(resolveTargetContract(p).strict_real_e2e,true);});
test('real Android exploration cannot opt into plaintext HTTP or skip its proxy CA',()=>{
 const p=profile();p.config_json.acquisition_mode='explore';p.config_json.capture_http_only=true;p.config_json.capture_origin='http://api.example.test';
 const errors=validateTargetPrerequisites(p,session(),'manifest').join(' ');
 assert.match(errors,/HTTPS capture/);assert.match(errors,/HTTPS capture_origin/);
 assert.equal(resolveTargetContract(p).require_proxy_certificate,true);
});
test('physical Android discovery rejects a stale plaintext capture even when its profile says explore',()=>{
 const p=profile();p.config_json.acquisition_mode='explore';p.config_json.capture_http_only=true;p.config_json.capture_origin='http://api.example.test';
 const s=session(),wire={...flow(s),url:'http://api.example.test/orders',tls_decrypted:false};
 assert.equal(discoveryCaptureRejection(wire,s,p),'unsupported_transport');
});
test('profile persistence rejects physical HTTP capture configuration',async t=>{
 const db=await database();t.after(()=>db.disconnect());const p=profile();p.config_json.capture_http_only=true;
 await assert.rejects(()=>upsertMobileProfile(db,p),/decrypted HTTPS capture/);
});
test('mobile preparation rejects an HTTP exploration target before any device action',async t=>{
 const db=await database();t.after(()=>db.disconnect());const p=profile();await upsertMobileProfile(db,p);
 await assert.rejects(()=>prepareMobileLab(db,{profile_id:p.id,authorized_base_url:'http://api.example.test',acquisition_mode:'explore'}),/HTTPS target/);
});
test('Java-only APK is not incorrectly rejected for missing native ABI',()=>assert.deepEqual(validateTargetPrerequisites(profile(),session(),'manifest'),[]));
test('incompatible native ABI rejected',()=>{const s=session();s.apk_native_abis=['arm64-v8a'];assert.match(validateTargetPrerequisites(profile(),s,'manifest').join(' '),/incompatible/);});
for (const field of ['apk_path','apk_source','apk_sha256','apk_signer_sha256','apk_package_name']) test(`missing ${field} blocks strict manifest`,()=>{const s=session();delete s[field];assert.ok(validateTargetPrerequisites(profile(),s,'manifest').length>0);});
test('device label is not an ADB serial',()=>{const p=profile(),s=session();delete p.adb_serial;delete s.device_id;p.device_name='just-a-label';assert.match(validateTargetPrerequisites(p,s,'manifest').join(' '),/adb_serial/);});
for (const phase of ['apk_install','app_launch','flow_run']) test(`capture requires persisted successful ${phase}`,()=>{const s=session();s.health_json[phase].ok=false;assert.ok(validateTargetPrerequisites(profile(),s,'capture').length>0);});
test('manifest validation precedes certificate provisioning',()=>{const s=session();s.certificate_evidence={};assert.deepEqual(validateTargetPrerequisites(profile(),s,'manifest'),[]);assert.ok(validateTargetPrerequisites(profile(),s,'prepare').length>0);});
test('relative and fully-qualified activities are equivalent',()=>assert.equal(normalizeActivity(pkg,'.MainActivity'),normalizeActivity(pkg,pkg+'/'+pkg+'.MainActivity')));
for (const expected of [{},{min_ui_nodes:NaN},{min_ui_nodes:0},{package:pkg,absent:true},{text:'Login',enabled:'true'},{not_a_field:'x'},{text:''},{text:'x',match:'regex'}]) test(`invalid expectation rejected: ${JSON.stringify(expected)}`,()=>assert.ok(validateExpectationShape(expected)));
test('selectors use conjunction, not OR',()=>assert.equal(matchesUiNode(observation().ui_tree[0],{resource_id:'login',text:'Logout'}),false));
test('resource suffix is exact path component',()=>assert.equal(matchesUiNode(observation().ui_tree[0],{resource_id:'gin'}),false));
test('contains matching must be explicitly requested',()=>{assert.equal(matchesUiNode(observation().ui_tree[0],{text:'Log'}),false);assert.equal(matchesUiNode(observation().ui_tree[0],{text:'Log',match:'contains'}),true);});
test('negative expectation detects present element',()=>assert.ok(validateStepExpectation(observation(),{text:'Login',absent:true})));
test('missing observation cannot satisfy assertion',()=>assert.ok(validateStepExpectation(null,{text:'Login'})));
test('valid observation passes strict validation',()=>assert.deepEqual(validateObservation(profile(),session(),observation()),[]));
for (const change of [{screenshot_base64:'hello'},{ui_tree:[]},{package:'other.app'}]) test(`invalid observation rejected: ${Object.keys(change)}`,()=>assert.ok(validateObservation(profile(),session(),{...observation(),...change}).length));
test('PNG signature distinguishes text',()=>{assert.ok(isPngScreenshot(PNG));assert.equal(isPngScreenshot(Buffer.from('not a screenshot').toString('base64')),false);});
for(const steps of [[],[{action:'wait',ms:1}],[{action:'tap',target:{resource_id:'login'},expect:{}}],[{action:'tap',expect:{text:'Login'}}],[{action:'swipe',x1:NaN,y1:0,x2:1,y2:1,expect:{text:'Login'}}],[{action:'tap',target:{resource_id:'login'},expect:{text:'Login'},timeout_ms:Infinity}],[{action:'type',target:{resource_id:'login'},value:{},expect:{text:'Login'}}]]) test(`malformed flow rejected before execution: ${JSON.stringify(steps)}`,()=>assert.ok(validateFlowSteps(steps,true).length));
test('valid deterministic flow accepted',()=>assert.deepEqual(validateFlowSteps([{action:'tap',target:{resource_id:'login'},expect:{text:'Login'},timeout_ms:0}],true),[]));
const mutations=[['wrong_capture_session',{capture_session_id:'old'}],['wrong_device',{device_id:'other'}],['invalid_tls_response_or_package',{app_package:'other'}],['invalid_tls_response_or_package',{tls_decrypted:false}],['invalid_tls_response_or_package',{response_status:null}],['invalid_tls_response_or_package',{response_status:0}],['invalid_tls_response_or_package',{response_status:'200'}],['invalid_tls_response_or_package',{method:'connect'}],['outside_authorized_hosts',{url:'https://outside.example/orders'}],['invalid_tls_response_or_package',{url:'https://user:pass@api.example.test/orders'}],['stale_or_invalid_timestamp',{started_at:'2000-01-01T00:00:00Z'}],['stale_or_invalid_timestamp',{started_at:'garbage'}]];
for(const [reason,change] of mutations) test(`capture rejection ${reason}: ${JSON.stringify(change)}`,()=>{const s=session();assert.equal(captureRejectionReason({...flow(s),...change},s,['api.example.test']),reason);});
test('current same-session allowed-host evidence accepted',()=>{const s=session();assert.equal(captureRejectionReason(flow(s),s,['api.example.test']),undefined);});
test('HTTPS scheme alone does not prove decrypted response',()=>assert.equal(isVerifiedDecryptedAppFlow({...flow(),tls_decrypted:undefined},pkg,true),false));
test('raw normalizer preserves capture provenance',()=>{const f=flow();assert.equal(normalizeRawFlow(f,0).capture_session_id,f.capture_session_id);assert.equal(normalizeRawFlow(null,0),null);});
test('pretty-printed JSON is parsed as JSON, not line-delimited',()=>assert.equal(parseFlowText(JSON.stringify([flow()],null,2),'flows.json').length,1));
test('partial last JSONL line deferred, not accepted',()=>assert.equal(parseFlowText(JSON.stringify(flow())+'\n{"method":','flows.jsonl').length,1));
test('malformed completed JSONL line fails closed',()=>assert.throws(()=>parseFlowText('{bad}\n','flows.jsonl'),/Malformed/));
