#!/usr/bin/env node
/** Deployment prerequisite check. Missing prerequisites are a failure, never a simulated PASS. */
import {access,readFile} from 'node:fs/promises';import {constants} from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');const results=[];
async function check(name,fn){try{await fn();results.push({name,ok:true});}catch(e){results.push({name,ok:false,error:String(e.message||e)});}}
await check('Linux isolated desktop runtime',()=>{if(process.platform!=='linux')throw Error('Use a Linux worker/VM; native Windows/macOS desktops are not shared.');});
await check('Chromium sandbox retained',()=>{if(process.getuid?.()===0 && process.env.BSTG_BROWSER_ALLOW_NO_SANDBOX!=='1')throw Error('Run the worker as a non-root user with Chromium sandbox support.');if(process.env.BSTG_BROWSER_ALLOW_NO_SANDBOX==='1')throw Error('Unsafe sandbox opt-out is for isolated test fixtures, not release acceptance.');});
for(const [name,variable]of [['Xvfb','BSTG_XVFB_BIN'],['x11vnc','BSTG_X11VNC_BIN'],['websockify','BSTG_WEBSOCKIFY_BIN']])await check(name,async()=>{const binary=process.env[variable]||name;const candidates=binary.includes('/')?[binary]:(process.env.PATH||'').split(path.delimiter).map(dir=>path.join(dir,binary));for(const c of candidates){if(await access(c,constants.X_OK).then(()=>true,()=>false))return;}throw Error('Executable missing: '+name);});
await check('Production Playwright and browser installed',async()=>{const require=createRequire(path.join(root,'server/package.json'));const {chromium}=require('playwright');await access(process.env.BSTG_CHROMIUM_EXECUTABLE||chromium.executablePath(),constants.X_OK);});
await check('Local noVNC static modules shipped',async()=>{await access(path.join(root,'public/vendor/novnc/core/rfb.js'));await access(path.join(root,'public/live-browser/viewer.js'));});
await check('Viewer access policy configured',()=>{const mode=process.env.BSTG_LIVE_ACCESS_MODE||'local';if(mode==='local')return;if(mode!=='proxy')throw Error('Unknown mode');if((process.env.BSTG_LIVE_PROXY_SECRET||'').length<32)throw Error('Proxy secret needs 32+ bytes');const origin=new URL(process.env.BSTG_PUBLIC_ORIGIN||'');if(origin.protocol!=='https:'||origin.origin!==process.env.BSTG_PUBLIC_ORIGIN)throw Error('Exact HTTPS origin required');});
console.log(JSON.stringify({ok:results.every(r=>r.ok),checks:results,note:'This checks prerequisites, not real-site acceptance or application-wide authentication.'},null,2));process.exitCode=results.every(r=>r.ok)?0:1;
